baseURL = 'https://dswithann.github.io'
languageCode = 'en-us'
title = 'Ann Naser Nabil '
theme = 'github-style-plus'
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
    author = "Ann Naser Nabil"
    description = "Let's have fun"
    github = "AnnNaserNabil"
    enableGithubFollowers = true
    twitter = "ann_naser_"
    linkedin = "ann-naser-nabil"
    email = "ann.n.nabil@gmail.com"
    lastmod = true
    userStatusEmoji = "☠️"
    favicon = "/images/avatar.jpeg"
    avatar = "/images/avatar.jpeg"
    location = "Dhaka, Bangladesh"
    enableGitalk = false
    enableLocalSearch = false
    sponsorLink = "https://www.linkedin.com/in/ann-naser-nabil"
#    customStyleFile = "your css file name"
#    gtmId = "your gtm id"
